src/apps/account/urls.py
from django.urls import path

from apps.account.views.auth import (
    DeactivateAccount,
    RecoveryCompleteView,
    RecoveryConfirmView,
    RecoveryDoneView,
    RecoveryView,
    UserLoginView,
    UserLogoutView,
    UserRegisterView,
)
from apps.account.views.profile import (
    UserDeleteView,
    UserProfileUpdateView,
)

app_name = "account"

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("logout/", UserLogoutView.as_view(), name="logout"),

    # Profile
    path('profile/delete', UserDeleteView.as_view(), name='profile_delete'),
    path('profile/edit', UserProfileUpdateView.as_view(), name='profile_edit'),
    path("deactivate/", DeactivateAccount.as_view(), name="profile_deactivate"),

    # Recovery
    path("recovery/", RecoveryView.as_view(), name="recovery"),
    path("recovery/done/", RecoveryDoneView.as_view(), name="password_reset_done"),
    path(
        "recovery/confirm/<uidb64>/<token>/",
        RecoveryConfirmView.as_view(),
        name="recovery_confirm",
    ),
    path("recovery/complete/", RecoveryCompleteView.as_view(),
         name="password_reset_complete"),
]

src/core/urls.py
from django.contrib import admin
from django.urls import include, path

from apps.common.views import NotFoundView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path("info/", include("apps.institutional.urls")),
    path("account/", include("apps.account.urls")),
    path("dashboard/", include("apps.monitor.urls")),
    path("buy/", include("apps.billing.urls")),
    path("manager/", include("apps.manager.urls")),
    path("", include("apps.converter.urls")),
    path("", include("apps.common.urls")),

]

handler404 = NotFoundView.as_view()

src/apps/security/models.py
# Create your models here.

src/apps/security/views.py
# Create your views here.

src/apps/security/templates/security/locked.html
{% extends 'common/base.html' %}

{% load widget_tweaks %}
{% load static %}
{% load i18n %}

{% block header %}{% endblock %}
{% block footer %}{% endblock %}

{% block content %}
<main class="min-h-screen p-4 flex flex-col items-center justify-center">
    <img
        class="w-full max-w-[1080px] max-h-full absolute blur-sm -z-10 opacity-5"
        src="{% static '/common/svg/logo/without_bg_icon_blue.svg' %}"
        alt="shortly logo"
    >

    <div class="flex items-start md:items-center gap-3 sm:gap-4 justify-center flex-col text-center max-w-md sm:max-w-xl">
        <h4 class="flex gap-3 text-start md:text-center items-center px-3 py-2 text-blue-500 font-bold text-lg sm:text-2xl">
            <span class="material-symbols-outlined font-bold rounded-full text-blue-500 text-xl sm:text-2xl">
                block
            </span>
            {% trans "Access temporarily blocked" %}
        </h4>

        <p class="text-sm text-start md:text-center sm:text-base leading-snug sm:leading-relaxed text-gray-700">
            {% trans "We detected multiple unsuccessful login attempts." %}
            <br>
            {% trans "For security reasons, your access has been temporarily blocked." %}
        </p>

        <p class="text-sm text-start md:text-center sm:text-base leading-snug sm:leading-relaxed text-gray-700">
            {% trans "Please wait a few minutes and try again." %}
            <br>
            {% trans "If you forgot your password, use the " %}
            <a href="{% url 'account:recovery' %}" class="outlined text-blue-500 cursor-pointer">
                {% trans "password recovery" %}
            </a>
        </p>

        <small class="text-xs text-start md:text-center sm:text-sm text-gray-400 leading-snug sm:leading-normal">
            {% trans "If you believe this is a mistake, please contact support." %}
        </small>
    </div>
</main>
{% endblock %}